/* Generated by Yosys 0.38 (git sha1 543faed9c8c, clang++ 17.0.6 -fPIC -Os) */

module axi_apb_bridge(axi_aclk, axi_aresetn, axi_awaddr, axi_awprot, axi_awvalid, axi_awready, axi_wdata, axi_wstrb, axi_wvalid, axi_wready, axi_bresp, axi_bvalid, axi_bready, axi_araddr, axi_arprot, axi_arvalid, axi_arready, axi_rdata, axi_rresp, axi_rvalid, axi_rready
, apb_paddr, apb_pwrite, apb_psel, apb_penable, apb_pwdata, apb_prdata, apb_pready, apb_pslverr);
  wire _0000_;
  wire _0001_;
  wire _0002_;
  wire _0003_;
  wire _0004_;
  wire _0005_;
  wire _0006_;
  wire _0007_;
  wire _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  output [31:0] apb_paddr;
  wire [31:0] apb_paddr;
  output apb_penable;
  wire apb_penable;
  input [31:0] apb_prdata;
  wire [31:0] apb_prdata;
  input apb_pready;
  wire apb_pready;
  output apb_psel;
  wire apb_psel;
  input apb_pslverr;
  wire apb_pslverr;
  output [31:0] apb_pwdata;
  wire [31:0] apb_pwdata;
  output apb_pwrite;
  wire apb_pwrite;
  input axi_aclk;
  wire axi_aclk;
  input [31:0] axi_araddr;
  wire [31:0] axi_araddr;
  input axi_aresetn;
  wire axi_aresetn;
  input [2:0] axi_arprot;
  wire [2:0] axi_arprot;
  output axi_arready;
  wire axi_arready;
  input axi_arvalid;
  wire axi_arvalid;
  input [31:0] axi_awaddr;
  wire [31:0] axi_awaddr;
  input [2:0] axi_awprot;
  wire [2:0] axi_awprot;
  output axi_awready;
  wire axi_awready;
  input axi_awvalid;
  wire axi_awvalid;
  input axi_bready;
  wire axi_bready;
  output [1:0] axi_bresp;
  wire [1:0] axi_bresp;
  output axi_bvalid;
  wire axi_bvalid;
  output [31:0] axi_rdata;
  wire [31:0] axi_rdata;
  input axi_rready;
  wire axi_rready;
  output [1:0] axi_rresp;
  wire [1:0] axi_rresp;
  output axi_rvalid;
  wire axi_rvalid;
  input [31:0] axi_wdata;
  wire [31:0] axi_wdata;
  output axi_wready;
  wire axi_wready;
  input [3:0] axi_wstrb;
  wire [3:0] axi_wstrb;
  input axi_wvalid;
  wire axi_wvalid;
  wire \captured_addr[0] ;
  wire \captured_addr[10] ;
  wire \captured_addr[11] ;
  wire \captured_addr[12] ;
  wire \captured_addr[13] ;
  wire \captured_addr[14] ;
  wire \captured_addr[15] ;
  wire \captured_addr[16] ;
  wire \captured_addr[17] ;
  wire \captured_addr[18] ;
  wire \captured_addr[19] ;
  wire \captured_addr[1] ;
  wire \captured_addr[20] ;
  wire \captured_addr[21] ;
  wire \captured_addr[22] ;
  wire \captured_addr[23] ;
  wire \captured_addr[24] ;
  wire \captured_addr[25] ;
  wire \captured_addr[26] ;
  wire \captured_addr[27] ;
  wire \captured_addr[28] ;
  wire \captured_addr[29] ;
  wire \captured_addr[2] ;
  wire \captured_addr[30] ;
  wire \captured_addr[31] ;
  wire \captured_addr[3] ;
  wire \captured_addr[4] ;
  wire \captured_addr[5] ;
  wire \captured_addr[6] ;
  wire \captured_addr[7] ;
  wire \captured_addr[8] ;
  wire \captured_addr[9] ;
  wire \captured_wdata[0] ;
  wire \captured_wdata[10] ;
  wire \captured_wdata[11] ;
  wire \captured_wdata[12] ;
  wire \captured_wdata[13] ;
  wire \captured_wdata[14] ;
  wire \captured_wdata[15] ;
  wire \captured_wdata[16] ;
  wire \captured_wdata[17] ;
  wire \captured_wdata[18] ;
  wire \captured_wdata[19] ;
  wire \captured_wdata[1] ;
  wire \captured_wdata[20] ;
  wire \captured_wdata[21] ;
  wire \captured_wdata[22] ;
  wire \captured_wdata[23] ;
  wire \captured_wdata[24] ;
  wire \captured_wdata[25] ;
  wire \captured_wdata[26] ;
  wire \captured_wdata[27] ;
  wire \captured_wdata[28] ;
  wire \captured_wdata[29] ;
  wire \captured_wdata[2] ;
  wire \captured_wdata[30] ;
  wire \captured_wdata[31] ;
  wire \captured_wdata[3] ;
  wire \captured_wdata[4] ;
  wire \captured_wdata[5] ;
  wire \captured_wdata[6] ;
  wire \captured_wdata[7] ;
  wire \captured_wdata[8] ;
  wire \captured_wdata[9] ;
  wire \current_state[0] ;
  wire \current_state[1] ;
  wire \current_state[2] ;
  sky130_fd_sc_hd__inv_2 _0418_ (
    .A(axi_wvalid),
    .Y(_0172_)
  );
  sky130_fd_sc_hd__buf_1 _0419_ (
    .A(\current_state[2] ),
    .X(_0173_)
  );
  sky130_fd_sc_hd__or3b_2 _0420_ (
    .A(_0173_),
    .B(\current_state[1] ),
    .C_N(\current_state[0] ),
    .X(_0174_)
  );
  sky130_fd_sc_hd__nor2_2 _0421_ (
    .A(_0172_),
    .B(_0174_),
    .Y(_0175_)
  );
  sky130_fd_sc_hd__buf_1 _0422_ (
    .A(_0175_),
    .X(_0003_)
  );
  sky130_fd_sc_hd__or3b_2 _0423_ (
    .A(_0173_),
    .B(\current_state[0] ),
    .C_N(\current_state[1] ),
    .X(_0176_)
  );
  sky130_fd_sc_hd__buf_1 _0424_ (
    .A(_0176_),
    .X(_0177_)
  );
  sky130_fd_sc_hd__or3b_2 _0425_ (
    .A(\current_state[0] ),
    .B(\current_state[1] ),
    .C_N(\current_state[2] ),
    .X(_0178_)
  );
  sky130_fd_sc_hd__buf_1 _0426_ (
    .A(_0178_),
    .X(_0179_)
  );
  sky130_fd_sc_hd__nand2_2 _0427_ (
    .A(_0177_),
    .B(_0179_),
    .Y(_0180_)
  );
  sky130_fd_sc_hd__buf_1 _0428_ (
    .A(_0180_),
    .X(_0001_)
  );
  sky130_fd_sc_hd__nor3_2 _0429_ (
    .A(_0173_),
    .B(\current_state[0] ),
    .C(\current_state[1] ),
    .Y(_0181_)
  );
  sky130_fd_sc_hd__and2_2 _0430_ (
    .A(axi_awvalid),
    .B(_0181_),
    .X(_0182_)
  );
  sky130_fd_sc_hd__buf_1 _0431_ (
    .A(_0182_),
    .X(_0417_)
  );
  sky130_fd_sc_hd__and2_2 _0432_ (
    .A(apb_pready),
    .B(_0001_),
    .X(_0183_)
  );
  sky130_fd_sc_hd__buf_1 _0433_ (
    .A(_0183_),
    .X(_0000_)
  );
  sky130_fd_sc_hd__inv_2 _0434_ (
    .A(axi_arvalid),
    .Y(_0184_)
  );
  sky130_fd_sc_hd__or4_2 _0435_ (
    .A(_0173_),
    .B(\current_state[0] ),
    .C(\current_state[1] ),
    .D(axi_awvalid),
    .X(_0185_)
  );
  sky130_fd_sc_hd__nor2_2 _0436_ (
    .A(_0184_),
    .B(_0185_),
    .Y(_0002_)
  );
  sky130_fd_sc_hd__nand2_2 _0437_ (
    .A(apb_pready),
    .B(axi_aresetn),
    .Y(_0186_)
  );
  sky130_fd_sc_hd__or2_2 _0438_ (
    .A(_0179_),
    .B(_0186_),
    .X(_0187_)
  );
  sky130_fd_sc_hd__buf_1 _0439_ (
    .A(_0187_),
    .X(_0188_)
  );
  sky130_fd_sc_hd__buf_1 _0440_ (
    .A(_0188_),
    .X(_0189_)
  );
  sky130_fd_sc_hd__mux2_2 _0441_ (
    .A0(apb_pslverr),
    .A1(axi_rresp[1]),
    .S(_0189_),
    .X(_0190_)
  );
  sky130_fd_sc_hd__buf_1 _0442_ (
    .A(_0190_),
    .X(_0114_)
  );
  sky130_fd_sc_hd__or2_2 _0443_ (
    .A(_0180_),
    .B(_0417_),
    .X(_0191_)
  );
  sky130_fd_sc_hd__nor2_2 _0444_ (
    .A(axi_arvalid),
    .B(_0185_),
    .Y(_0192_)
  );
  sky130_fd_sc_hd__inv_2 _0445_ (
    .A(apb_pready),
    .Y(_0193_)
  );
  sky130_fd_sc_hd__nor3b_2 _0446_ (
    .A(_0173_),
    .B(\current_state[0] ),
    .C_N(\current_state[1] ),
    .Y(_0194_)
  );
  sky130_fd_sc_hd__and4bb_2 _0447_ (
    .A_N(_0173_),
    .B_N(axi_bready),
    .C(\current_state[1] ),
    .D(\current_state[0] ),
    .X(_0195_)
  );
  sky130_fd_sc_hd__a21o_2 _0448_ (
    .A1(_0193_),
    .A2(_0194_),
    .B1(_0195_),
    .X(_0196_)
  );
  sky130_fd_sc_hd__or4bb_2 _0449_ (
    .A(axi_rready),
    .B(\current_state[1] ),
    .C_N(\current_state[0] ),
    .D_N(_0173_),
    .X(_0197_)
  );
  sky130_fd_sc_hd__o221a_2 _0450_ (
    .A1(axi_wvalid),
    .A2(_0174_),
    .B1(_0179_),
    .B2(apb_pready),
    .C1(_0197_),
    .X(_0198_)
  );
  sky130_fd_sc_hd__or3b_2 _0451_ (
    .A(_0192_),
    .B(_0196_),
    .C_N(_0198_),
    .X(_0199_)
  );
  sky130_fd_sc_hd__mux2_2 _0452_ (
    .A0(_0191_),
    .A1(\current_state[0] ),
    .S(_0199_),
    .X(_0200_)
  );
  sky130_fd_sc_hd__buf_1 _0453_ (
    .A(_0200_),
    .X(_0115_)
  );
  sky130_fd_sc_hd__buf_1 _0454_ (
    .A(_0177_),
    .X(_0201_)
  );
  sky130_fd_sc_hd__and2_2 _0455_ (
    .A(_0174_),
    .B(_0201_),
    .X(_0202_)
  );
  sky130_fd_sc_hd__o21bai_2 _0456_ (
    .A1(_0199_),
    .A2(_0202_),
    .B1_N(_0196_),
    .Y(_0116_)
  );
  sky130_fd_sc_hd__nand2_2 _0457_ (
    .A(_0179_),
    .B(_0185_),
    .Y(_0203_)
  );
  sky130_fd_sc_hd__mux2_2 _0458_ (
    .A0(_0203_),
    .A1(_0173_),
    .S(_0199_),
    .X(_0204_)
  );
  sky130_fd_sc_hd__buf_1 _0459_ (
    .A(_0204_),
    .X(_0117_)
  );
  sky130_fd_sc_hd__or3b_2 _0460_ (
    .A(_0196_),
    .B(_0173_),
    .C_N(\current_state[1] ),
    .X(_0205_)
  );
  sky130_fd_sc_hd__a22o_2 _0461_ (
    .A1(apb_pready),
    .A2(_0194_),
    .B1(_0205_),
    .B2(axi_bvalid),
    .X(_0118_)
  );
  sky130_fd_sc_hd__mux2_2 _0462_ (
    .A0(apb_prdata[0]),
    .A1(axi_rdata[0]),
    .S(_0189_),
    .X(_0206_)
  );
  sky130_fd_sc_hd__buf_1 _0463_ (
    .A(_0206_),
    .X(_0119_)
  );
  sky130_fd_sc_hd__mux2_2 _0464_ (
    .A0(apb_prdata[1]),
    .A1(axi_rdata[1]),
    .S(_0189_),
    .X(_0207_)
  );
  sky130_fd_sc_hd__buf_1 _0465_ (
    .A(_0207_),
    .X(_0120_)
  );
  sky130_fd_sc_hd__mux2_2 _0466_ (
    .A0(apb_prdata[2]),
    .A1(axi_rdata[2]),
    .S(_0189_),
    .X(_0208_)
  );
  sky130_fd_sc_hd__buf_1 _0467_ (
    .A(_0208_),
    .X(_0121_)
  );
  sky130_fd_sc_hd__mux2_2 _0468_ (
    .A0(apb_prdata[3]),
    .A1(axi_rdata[3]),
    .S(_0189_),
    .X(_0209_)
  );
  sky130_fd_sc_hd__buf_1 _0469_ (
    .A(_0209_),
    .X(_0122_)
  );
  sky130_fd_sc_hd__mux2_2 _0470_ (
    .A0(apb_prdata[4]),
    .A1(axi_rdata[4]),
    .S(_0189_),
    .X(_0210_)
  );
  sky130_fd_sc_hd__buf_1 _0471_ (
    .A(_0210_),
    .X(_0123_)
  );
  sky130_fd_sc_hd__mux2_2 _0472_ (
    .A0(apb_prdata[5]),
    .A1(axi_rdata[5]),
    .S(_0189_),
    .X(_0211_)
  );
  sky130_fd_sc_hd__buf_1 _0473_ (
    .A(_0211_),
    .X(_0124_)
  );
  sky130_fd_sc_hd__mux2_2 _0474_ (
    .A0(apb_prdata[6]),
    .A1(axi_rdata[6]),
    .S(_0189_),
    .X(_0212_)
  );
  sky130_fd_sc_hd__buf_1 _0475_ (
    .A(_0212_),
    .X(_0125_)
  );
  sky130_fd_sc_hd__mux2_2 _0476_ (
    .A0(apb_prdata[7]),
    .A1(axi_rdata[7]),
    .S(_0189_),
    .X(_0213_)
  );
  sky130_fd_sc_hd__buf_1 _0477_ (
    .A(_0213_),
    .X(_0126_)
  );
  sky130_fd_sc_hd__mux2_2 _0478_ (
    .A0(apb_prdata[8]),
    .A1(axi_rdata[8]),
    .S(_0189_),
    .X(_0214_)
  );
  sky130_fd_sc_hd__buf_1 _0479_ (
    .A(_0214_),
    .X(_0127_)
  );
  sky130_fd_sc_hd__buf_1 _0480_ (
    .A(_0188_),
    .X(_0215_)
  );
  sky130_fd_sc_hd__mux2_2 _0481_ (
    .A0(apb_prdata[9]),
    .A1(axi_rdata[9]),
    .S(_0215_),
    .X(_0216_)
  );
  sky130_fd_sc_hd__buf_1 _0482_ (
    .A(_0216_),
    .X(_0128_)
  );
  sky130_fd_sc_hd__mux2_2 _0483_ (
    .A0(apb_prdata[10]),
    .A1(axi_rdata[10]),
    .S(_0215_),
    .X(_0217_)
  );
  sky130_fd_sc_hd__buf_1 _0484_ (
    .A(_0217_),
    .X(_0129_)
  );
  sky130_fd_sc_hd__mux2_2 _0485_ (
    .A0(apb_prdata[11]),
    .A1(axi_rdata[11]),
    .S(_0215_),
    .X(_0218_)
  );
  sky130_fd_sc_hd__buf_1 _0486_ (
    .A(_0218_),
    .X(_0130_)
  );
  sky130_fd_sc_hd__mux2_2 _0487_ (
    .A0(apb_prdata[12]),
    .A1(axi_rdata[12]),
    .S(_0215_),
    .X(_0219_)
  );
  sky130_fd_sc_hd__buf_1 _0488_ (
    .A(_0219_),
    .X(_0131_)
  );
  sky130_fd_sc_hd__mux2_2 _0489_ (
    .A0(apb_prdata[13]),
    .A1(axi_rdata[13]),
    .S(_0215_),
    .X(_0220_)
  );
  sky130_fd_sc_hd__buf_1 _0490_ (
    .A(_0220_),
    .X(_0132_)
  );
  sky130_fd_sc_hd__mux2_2 _0491_ (
    .A0(apb_prdata[14]),
    .A1(axi_rdata[14]),
    .S(_0215_),
    .X(_0221_)
  );
  sky130_fd_sc_hd__buf_1 _0492_ (
    .A(_0221_),
    .X(_0133_)
  );
  sky130_fd_sc_hd__mux2_2 _0493_ (
    .A0(apb_prdata[15]),
    .A1(axi_rdata[15]),
    .S(_0215_),
    .X(_0222_)
  );
  sky130_fd_sc_hd__buf_1 _0494_ (
    .A(_0222_),
    .X(_0134_)
  );
  sky130_fd_sc_hd__mux2_2 _0495_ (
    .A0(apb_prdata[16]),
    .A1(axi_rdata[16]),
    .S(_0215_),
    .X(_0223_)
  );
  sky130_fd_sc_hd__buf_1 _0496_ (
    .A(_0223_),
    .X(_0135_)
  );
  sky130_fd_sc_hd__mux2_2 _0497_ (
    .A0(apb_prdata[17]),
    .A1(axi_rdata[17]),
    .S(_0215_),
    .X(_0224_)
  );
  sky130_fd_sc_hd__buf_1 _0498_ (
    .A(_0224_),
    .X(_0136_)
  );
  sky130_fd_sc_hd__mux2_2 _0499_ (
    .A0(apb_prdata[18]),
    .A1(axi_rdata[18]),
    .S(_0215_),
    .X(_0225_)
  );
  sky130_fd_sc_hd__buf_1 _0500_ (
    .A(_0225_),
    .X(_0137_)
  );
  sky130_fd_sc_hd__buf_1 _0501_ (
    .A(_0188_),
    .X(_0226_)
  );
  sky130_fd_sc_hd__mux2_2 _0502_ (
    .A0(apb_prdata[19]),
    .A1(axi_rdata[19]),
    .S(_0226_),
    .X(_0227_)
  );
  sky130_fd_sc_hd__buf_1 _0503_ (
    .A(_0227_),
    .X(_0138_)
  );
  sky130_fd_sc_hd__mux2_2 _0504_ (
    .A0(apb_prdata[20]),
    .A1(axi_rdata[20]),
    .S(_0226_),
    .X(_0228_)
  );
  sky130_fd_sc_hd__buf_1 _0505_ (
    .A(_0228_),
    .X(_0139_)
  );
  sky130_fd_sc_hd__mux2_2 _0506_ (
    .A0(apb_prdata[21]),
    .A1(axi_rdata[21]),
    .S(_0226_),
    .X(_0229_)
  );
  sky130_fd_sc_hd__buf_1 _0507_ (
    .A(_0229_),
    .X(_0140_)
  );
  sky130_fd_sc_hd__mux2_2 _0508_ (
    .A0(apb_prdata[22]),
    .A1(axi_rdata[22]),
    .S(_0226_),
    .X(_0230_)
  );
  sky130_fd_sc_hd__buf_1 _0509_ (
    .A(_0230_),
    .X(_0141_)
  );
  sky130_fd_sc_hd__mux2_2 _0510_ (
    .A0(apb_prdata[23]),
    .A1(axi_rdata[23]),
    .S(_0226_),
    .X(_0231_)
  );
  sky130_fd_sc_hd__buf_1 _0511_ (
    .A(_0231_),
    .X(_0142_)
  );
  sky130_fd_sc_hd__mux2_2 _0512_ (
    .A0(apb_prdata[24]),
    .A1(axi_rdata[24]),
    .S(_0226_),
    .X(_0232_)
  );
  sky130_fd_sc_hd__buf_1 _0513_ (
    .A(_0232_),
    .X(_0143_)
  );
  sky130_fd_sc_hd__mux2_2 _0514_ (
    .A0(apb_prdata[25]),
    .A1(axi_rdata[25]),
    .S(_0226_),
    .X(_0233_)
  );
  sky130_fd_sc_hd__buf_1 _0515_ (
    .A(_0233_),
    .X(_0144_)
  );
  sky130_fd_sc_hd__mux2_2 _0516_ (
    .A0(apb_prdata[26]),
    .A1(axi_rdata[26]),
    .S(_0226_),
    .X(_0234_)
  );
  sky130_fd_sc_hd__buf_1 _0517_ (
    .A(_0234_),
    .X(_0145_)
  );
  sky130_fd_sc_hd__mux2_2 _0518_ (
    .A0(apb_prdata[27]),
    .A1(axi_rdata[27]),
    .S(_0226_),
    .X(_0235_)
  );
  sky130_fd_sc_hd__buf_1 _0519_ (
    .A(_0235_),
    .X(_0146_)
  );
  sky130_fd_sc_hd__mux2_2 _0520_ (
    .A0(apb_prdata[28]),
    .A1(axi_rdata[28]),
    .S(_0226_),
    .X(_0236_)
  );
  sky130_fd_sc_hd__buf_1 _0521_ (
    .A(_0236_),
    .X(_0147_)
  );
  sky130_fd_sc_hd__mux2_2 _0522_ (
    .A0(apb_prdata[29]),
    .A1(axi_rdata[29]),
    .S(_0188_),
    .X(_0237_)
  );
  sky130_fd_sc_hd__buf_1 _0523_ (
    .A(_0237_),
    .X(_0148_)
  );
  sky130_fd_sc_hd__mux2_2 _0524_ (
    .A0(apb_prdata[30]),
    .A1(axi_rdata[30]),
    .S(_0188_),
    .X(_0238_)
  );
  sky130_fd_sc_hd__buf_1 _0525_ (
    .A(_0238_),
    .X(_0149_)
  );
  sky130_fd_sc_hd__mux2_2 _0526_ (
    .A0(apb_prdata[31]),
    .A1(axi_rdata[31]),
    .S(_0188_),
    .X(_0239_)
  );
  sky130_fd_sc_hd__buf_1 _0527_ (
    .A(_0239_),
    .X(_0150_)
  );
  sky130_fd_sc_hd__or2_2 _0528_ (
    .A(_0177_),
    .B(_0186_),
    .X(_0240_)
  );
  sky130_fd_sc_hd__mux2_2 _0529_ (
    .A0(apb_pslverr),
    .A1(axi_bresp[1]),
    .S(_0240_),
    .X(_0241_)
  );
  sky130_fd_sc_hd__buf_1 _0530_ (
    .A(_0241_),
    .X(_0151_)
  );
  sky130_fd_sc_hd__o21ba_2 _0531_ (
    .A1(_0193_),
    .A2(_0179_),
    .B1_N(axi_rvalid),
    .X(_0242_)
  );
  sky130_fd_sc_hd__and4b_2 _0532_ (
    .A_N(\current_state[1] ),
    .B(\current_state[0] ),
    .C(_0173_),
    .D(axi_rready),
    .X(_0243_)
  );
  sky130_fd_sc_hd__nor2_2 _0533_ (
    .A(_0242_),
    .B(_0243_),
    .Y(_0152_)
  );
  sky130_fd_sc_hd__mux2_2 _0534_ (
    .A0(apb_paddr[0]),
    .A1(\captured_addr[0] ),
    .S(_0001_),
    .X(_0244_)
  );
  sky130_fd_sc_hd__buf_1 _0535_ (
    .A(_0244_),
    .X(_0153_)
  );
  sky130_fd_sc_hd__mux2_2 _0536_ (
    .A0(apb_paddr[1]),
    .A1(\captured_addr[1] ),
    .S(_0001_),
    .X(_0245_)
  );
  sky130_fd_sc_hd__buf_1 _0537_ (
    .A(_0245_),
    .X(_0154_)
  );
  sky130_fd_sc_hd__mux2_2 _0538_ (
    .A0(apb_paddr[2]),
    .A1(\captured_addr[2] ),
    .S(_0001_),
    .X(_0246_)
  );
  sky130_fd_sc_hd__buf_1 _0539_ (
    .A(_0246_),
    .X(_0155_)
  );
  sky130_fd_sc_hd__mux2_2 _0540_ (
    .A0(apb_paddr[3]),
    .A1(\captured_addr[3] ),
    .S(_0001_),
    .X(_0247_)
  );
  sky130_fd_sc_hd__buf_1 _0541_ (
    .A(_0247_),
    .X(_0156_)
  );
  sky130_fd_sc_hd__mux2_2 _0542_ (
    .A0(apb_paddr[4]),
    .A1(\captured_addr[4] ),
    .S(_0001_),
    .X(_0248_)
  );
  sky130_fd_sc_hd__buf_1 _0543_ (
    .A(_0248_),
    .X(_0157_)
  );
  sky130_fd_sc_hd__mux2_2 _0544_ (
    .A0(apb_paddr[5]),
    .A1(\captured_addr[5] ),
    .S(_0001_),
    .X(_0249_)
  );
  sky130_fd_sc_hd__buf_1 _0545_ (
    .A(_0249_),
    .X(_0158_)
  );
  sky130_fd_sc_hd__mux2_2 _0546_ (
    .A0(apb_paddr[6]),
    .A1(\captured_addr[6] ),
    .S(_0001_),
    .X(_0250_)
  );
  sky130_fd_sc_hd__buf_1 _0547_ (
    .A(_0250_),
    .X(_0159_)
  );
  sky130_fd_sc_hd__mux2_2 _0548_ (
    .A0(apb_paddr[7]),
    .A1(\captured_addr[7] ),
    .S(_0001_),
    .X(_0251_)
  );
  sky130_fd_sc_hd__buf_1 _0549_ (
    .A(_0251_),
    .X(_0160_)
  );
  sky130_fd_sc_hd__buf_1 _0550_ (
    .A(_0180_),
    .X(_0252_)
  );
  sky130_fd_sc_hd__mux2_2 _0551_ (
    .A0(apb_paddr[8]),
    .A1(\captured_addr[8] ),
    .S(_0252_),
    .X(_0253_)
  );
  sky130_fd_sc_hd__buf_1 _0552_ (
    .A(_0253_),
    .X(_0161_)
  );
  sky130_fd_sc_hd__mux2_2 _0553_ (
    .A0(apb_paddr[9]),
    .A1(\captured_addr[9] ),
    .S(_0252_),
    .X(_0254_)
  );
  sky130_fd_sc_hd__buf_1 _0554_ (
    .A(_0254_),
    .X(_0162_)
  );
  sky130_fd_sc_hd__mux2_2 _0555_ (
    .A0(apb_paddr[10]),
    .A1(\captured_addr[10] ),
    .S(_0252_),
    .X(_0255_)
  );
  sky130_fd_sc_hd__buf_1 _0556_ (
    .A(_0255_),
    .X(_0163_)
  );
  sky130_fd_sc_hd__mux2_2 _0557_ (
    .A0(apb_paddr[11]),
    .A1(\captured_addr[11] ),
    .S(_0252_),
    .X(_0256_)
  );
  sky130_fd_sc_hd__buf_1 _0558_ (
    .A(_0256_),
    .X(_0164_)
  );
  sky130_fd_sc_hd__mux2_2 _0559_ (
    .A0(apb_paddr[12]),
    .A1(\captured_addr[12] ),
    .S(_0252_),
    .X(_0257_)
  );
  sky130_fd_sc_hd__buf_1 _0560_ (
    .A(_0257_),
    .X(_0165_)
  );
  sky130_fd_sc_hd__mux2_2 _0561_ (
    .A0(apb_paddr[13]),
    .A1(\captured_addr[13] ),
    .S(_0252_),
    .X(_0258_)
  );
  sky130_fd_sc_hd__buf_1 _0562_ (
    .A(_0258_),
    .X(_0166_)
  );
  sky130_fd_sc_hd__mux2_2 _0563_ (
    .A0(apb_paddr[14]),
    .A1(\captured_addr[14] ),
    .S(_0252_),
    .X(_0259_)
  );
  sky130_fd_sc_hd__buf_1 _0564_ (
    .A(_0259_),
    .X(_0167_)
  );
  sky130_fd_sc_hd__mux2_2 _0565_ (
    .A0(apb_paddr[15]),
    .A1(\captured_addr[15] ),
    .S(_0252_),
    .X(_0260_)
  );
  sky130_fd_sc_hd__buf_1 _0566_ (
    .A(_0260_),
    .X(_0168_)
  );
  sky130_fd_sc_hd__mux2_2 _0567_ (
    .A0(apb_paddr[16]),
    .A1(\captured_addr[16] ),
    .S(_0252_),
    .X(_0261_)
  );
  sky130_fd_sc_hd__buf_1 _0568_ (
    .A(_0261_),
    .X(_0169_)
  );
  sky130_fd_sc_hd__mux2_2 _0569_ (
    .A0(apb_paddr[17]),
    .A1(\captured_addr[17] ),
    .S(_0252_),
    .X(_0262_)
  );
  sky130_fd_sc_hd__buf_1 _0570_ (
    .A(_0262_),
    .X(_0170_)
  );
  sky130_fd_sc_hd__buf_1 _0571_ (
    .A(_0180_),
    .X(_0263_)
  );
  sky130_fd_sc_hd__mux2_2 _0572_ (
    .A0(apb_paddr[18]),
    .A1(\captured_addr[18] ),
    .S(_0263_),
    .X(_0264_)
  );
  sky130_fd_sc_hd__buf_1 _0573_ (
    .A(_0264_),
    .X(_0171_)
  );
  sky130_fd_sc_hd__mux2_2 _0574_ (
    .A0(apb_paddr[19]),
    .A1(\captured_addr[19] ),
    .S(_0263_),
    .X(_0265_)
  );
  sky130_fd_sc_hd__buf_1 _0575_ (
    .A(_0265_),
    .X(_0004_)
  );
  sky130_fd_sc_hd__mux2_2 _0576_ (
    .A0(apb_paddr[20]),
    .A1(\captured_addr[20] ),
    .S(_0263_),
    .X(_0266_)
  );
  sky130_fd_sc_hd__buf_1 _0577_ (
    .A(_0266_),
    .X(_0005_)
  );
  sky130_fd_sc_hd__mux2_2 _0578_ (
    .A0(apb_paddr[21]),
    .A1(\captured_addr[21] ),
    .S(_0263_),
    .X(_0267_)
  );
  sky130_fd_sc_hd__buf_1 _0579_ (
    .A(_0267_),
    .X(_0006_)
  );
  sky130_fd_sc_hd__mux2_2 _0580_ (
    .A0(apb_paddr[22]),
    .A1(\captured_addr[22] ),
    .S(_0263_),
    .X(_0268_)
  );
  sky130_fd_sc_hd__buf_1 _0581_ (
    .A(_0268_),
    .X(_0007_)
  );
  sky130_fd_sc_hd__mux2_2 _0582_ (
    .A0(apb_paddr[23]),
    .A1(\captured_addr[23] ),
    .S(_0263_),
    .X(_0269_)
  );
  sky130_fd_sc_hd__buf_1 _0583_ (
    .A(_0269_),
    .X(_0008_)
  );
  sky130_fd_sc_hd__mux2_2 _0584_ (
    .A0(apb_paddr[24]),
    .A1(\captured_addr[24] ),
    .S(_0263_),
    .X(_0270_)
  );
  sky130_fd_sc_hd__buf_1 _0585_ (
    .A(_0270_),
    .X(_0009_)
  );
  sky130_fd_sc_hd__mux2_2 _0586_ (
    .A0(apb_paddr[25]),
    .A1(\captured_addr[25] ),
    .S(_0263_),
    .X(_0271_)
  );
  sky130_fd_sc_hd__buf_1 _0587_ (
    .A(_0271_),
    .X(_0010_)
  );
  sky130_fd_sc_hd__mux2_2 _0588_ (
    .A0(apb_paddr[26]),
    .A1(\captured_addr[26] ),
    .S(_0263_),
    .X(_0272_)
  );
  sky130_fd_sc_hd__buf_1 _0589_ (
    .A(_0272_),
    .X(_0011_)
  );
  sky130_fd_sc_hd__mux2_2 _0590_ (
    .A0(apb_paddr[27]),
    .A1(\captured_addr[27] ),
    .S(_0263_),
    .X(_0273_)
  );
  sky130_fd_sc_hd__buf_1 _0591_ (
    .A(_0273_),
    .X(_0012_)
  );
  sky130_fd_sc_hd__mux2_2 _0592_ (
    .A0(apb_paddr[28]),
    .A1(\captured_addr[28] ),
    .S(_0180_),
    .X(_0274_)
  );
  sky130_fd_sc_hd__buf_1 _0593_ (
    .A(_0274_),
    .X(_0013_)
  );
  sky130_fd_sc_hd__mux2_2 _0594_ (
    .A0(apb_paddr[29]),
    .A1(\captured_addr[29] ),
    .S(_0180_),
    .X(_0275_)
  );
  sky130_fd_sc_hd__buf_1 _0595_ (
    .A(_0275_),
    .X(_0014_)
  );
  sky130_fd_sc_hd__mux2_2 _0596_ (
    .A0(apb_paddr[30]),
    .A1(\captured_addr[30] ),
    .S(_0180_),
    .X(_0276_)
  );
  sky130_fd_sc_hd__buf_1 _0597_ (
    .A(_0276_),
    .X(_0015_)
  );
  sky130_fd_sc_hd__mux2_2 _0598_ (
    .A0(apb_paddr[31]),
    .A1(\captured_addr[31] ),
    .S(_0180_),
    .X(_0277_)
  );
  sky130_fd_sc_hd__buf_1 _0599_ (
    .A(_0277_),
    .X(_0016_)
  );
  sky130_fd_sc_hd__a21o_2 _0600_ (
    .A1(apb_pwrite),
    .A2(_0179_),
    .B1(_0194_),
    .X(_0017_)
  );
  sky130_fd_sc_hd__mux2_2 _0601_ (
    .A0(\captured_wdata[0] ),
    .A1(apb_pwdata[0]),
    .S(_0201_),
    .X(_0278_)
  );
  sky130_fd_sc_hd__buf_1 _0602_ (
    .A(_0278_),
    .X(_0018_)
  );
  sky130_fd_sc_hd__mux2_2 _0603_ (
    .A0(\captured_wdata[1] ),
    .A1(apb_pwdata[1]),
    .S(_0201_),
    .X(_0279_)
  );
  sky130_fd_sc_hd__buf_1 _0604_ (
    .A(_0279_),
    .X(_0019_)
  );
  sky130_fd_sc_hd__mux2_2 _0605_ (
    .A0(\captured_wdata[2] ),
    .A1(apb_pwdata[2]),
    .S(_0201_),
    .X(_0280_)
  );
  sky130_fd_sc_hd__buf_1 _0606_ (
    .A(_0280_),
    .X(_0020_)
  );
  sky130_fd_sc_hd__mux2_2 _0607_ (
    .A0(\captured_wdata[3] ),
    .A1(apb_pwdata[3]),
    .S(_0201_),
    .X(_0281_)
  );
  sky130_fd_sc_hd__buf_1 _0608_ (
    .A(_0281_),
    .X(_0021_)
  );
  sky130_fd_sc_hd__mux2_2 _0609_ (
    .A0(\captured_wdata[4] ),
    .A1(apb_pwdata[4]),
    .S(_0201_),
    .X(_0282_)
  );
  sky130_fd_sc_hd__buf_1 _0610_ (
    .A(_0282_),
    .X(_0022_)
  );
  sky130_fd_sc_hd__mux2_2 _0611_ (
    .A0(\captured_wdata[5] ),
    .A1(apb_pwdata[5]),
    .S(_0201_),
    .X(_0283_)
  );
  sky130_fd_sc_hd__buf_1 _0612_ (
    .A(_0283_),
    .X(_0023_)
  );
  sky130_fd_sc_hd__mux2_2 _0613_ (
    .A0(\captured_wdata[6] ),
    .A1(apb_pwdata[6]),
    .S(_0201_),
    .X(_0284_)
  );
  sky130_fd_sc_hd__buf_1 _0614_ (
    .A(_0284_),
    .X(_0024_)
  );
  sky130_fd_sc_hd__mux2_2 _0615_ (
    .A0(\captured_wdata[7] ),
    .A1(apb_pwdata[7]),
    .S(_0201_),
    .X(_0285_)
  );
  sky130_fd_sc_hd__buf_1 _0616_ (
    .A(_0285_),
    .X(_0025_)
  );
  sky130_fd_sc_hd__mux2_2 _0617_ (
    .A0(\captured_wdata[8] ),
    .A1(apb_pwdata[8]),
    .S(_0201_),
    .X(_0286_)
  );
  sky130_fd_sc_hd__buf_1 _0618_ (
    .A(_0286_),
    .X(_0026_)
  );
  sky130_fd_sc_hd__buf_1 _0619_ (
    .A(_0177_),
    .X(_0287_)
  );
  sky130_fd_sc_hd__mux2_2 _0620_ (
    .A0(\captured_wdata[9] ),
    .A1(apb_pwdata[9]),
    .S(_0287_),
    .X(_0288_)
  );
  sky130_fd_sc_hd__buf_1 _0621_ (
    .A(_0288_),
    .X(_0027_)
  );
  sky130_fd_sc_hd__mux2_2 _0622_ (
    .A0(\captured_wdata[10] ),
    .A1(apb_pwdata[10]),
    .S(_0287_),
    .X(_0289_)
  );
  sky130_fd_sc_hd__buf_1 _0623_ (
    .A(_0289_),
    .X(_0028_)
  );
  sky130_fd_sc_hd__mux2_2 _0624_ (
    .A0(\captured_wdata[11] ),
    .A1(apb_pwdata[11]),
    .S(_0287_),
    .X(_0290_)
  );
  sky130_fd_sc_hd__buf_1 _0625_ (
    .A(_0290_),
    .X(_0029_)
  );
  sky130_fd_sc_hd__mux2_2 _0626_ (
    .A0(\captured_wdata[12] ),
    .A1(apb_pwdata[12]),
    .S(_0287_),
    .X(_0291_)
  );
  sky130_fd_sc_hd__buf_1 _0627_ (
    .A(_0291_),
    .X(_0030_)
  );
  sky130_fd_sc_hd__mux2_2 _0628_ (
    .A0(\captured_wdata[13] ),
    .A1(apb_pwdata[13]),
    .S(_0287_),
    .X(_0292_)
  );
  sky130_fd_sc_hd__buf_1 _0629_ (
    .A(_0292_),
    .X(_0031_)
  );
  sky130_fd_sc_hd__mux2_2 _0630_ (
    .A0(\captured_wdata[14] ),
    .A1(apb_pwdata[14]),
    .S(_0287_),
    .X(_0293_)
  );
  sky130_fd_sc_hd__buf_1 _0631_ (
    .A(_0293_),
    .X(_0032_)
  );
  sky130_fd_sc_hd__mux2_2 _0632_ (
    .A0(\captured_wdata[15] ),
    .A1(apb_pwdata[15]),
    .S(_0287_),
    .X(_0294_)
  );
  sky130_fd_sc_hd__buf_1 _0633_ (
    .A(_0294_),
    .X(_0033_)
  );
  sky130_fd_sc_hd__mux2_2 _0634_ (
    .A0(\captured_wdata[16] ),
    .A1(apb_pwdata[16]),
    .S(_0287_),
    .X(_0295_)
  );
  sky130_fd_sc_hd__buf_1 _0635_ (
    .A(_0295_),
    .X(_0034_)
  );
  sky130_fd_sc_hd__mux2_2 _0636_ (
    .A0(\captured_wdata[17] ),
    .A1(apb_pwdata[17]),
    .S(_0287_),
    .X(_0296_)
  );
  sky130_fd_sc_hd__buf_1 _0637_ (
    .A(_0296_),
    .X(_0035_)
  );
  sky130_fd_sc_hd__mux2_2 _0638_ (
    .A0(\captured_wdata[18] ),
    .A1(apb_pwdata[18]),
    .S(_0287_),
    .X(_0297_)
  );
  sky130_fd_sc_hd__buf_1 _0639_ (
    .A(_0297_),
    .X(_0036_)
  );
  sky130_fd_sc_hd__buf_1 _0640_ (
    .A(_0177_),
    .X(_0298_)
  );
  sky130_fd_sc_hd__mux2_2 _0641_ (
    .A0(\captured_wdata[19] ),
    .A1(apb_pwdata[19]),
    .S(_0298_),
    .X(_0299_)
  );
  sky130_fd_sc_hd__buf_1 _0642_ (
    .A(_0299_),
    .X(_0037_)
  );
  sky130_fd_sc_hd__mux2_2 _0643_ (
    .A0(\captured_wdata[20] ),
    .A1(apb_pwdata[20]),
    .S(_0298_),
    .X(_0300_)
  );
  sky130_fd_sc_hd__buf_1 _0644_ (
    .A(_0300_),
    .X(_0038_)
  );
  sky130_fd_sc_hd__mux2_2 _0645_ (
    .A0(\captured_wdata[21] ),
    .A1(apb_pwdata[21]),
    .S(_0298_),
    .X(_0301_)
  );
  sky130_fd_sc_hd__buf_1 _0646_ (
    .A(_0301_),
    .X(_0039_)
  );
  sky130_fd_sc_hd__mux2_2 _0647_ (
    .A0(\captured_wdata[22] ),
    .A1(apb_pwdata[22]),
    .S(_0298_),
    .X(_0302_)
  );
  sky130_fd_sc_hd__buf_1 _0648_ (
    .A(_0302_),
    .X(_0040_)
  );
  sky130_fd_sc_hd__mux2_2 _0649_ (
    .A0(\captured_wdata[23] ),
    .A1(apb_pwdata[23]),
    .S(_0298_),
    .X(_0303_)
  );
  sky130_fd_sc_hd__buf_1 _0650_ (
    .A(_0303_),
    .X(_0041_)
  );
  sky130_fd_sc_hd__mux2_2 _0651_ (
    .A0(\captured_wdata[24] ),
    .A1(apb_pwdata[24]),
    .S(_0298_),
    .X(_0304_)
  );
  sky130_fd_sc_hd__buf_1 _0652_ (
    .A(_0304_),
    .X(_0042_)
  );
  sky130_fd_sc_hd__mux2_2 _0653_ (
    .A0(\captured_wdata[25] ),
    .A1(apb_pwdata[25]),
    .S(_0298_),
    .X(_0305_)
  );
  sky130_fd_sc_hd__buf_1 _0654_ (
    .A(_0305_),
    .X(_0043_)
  );
  sky130_fd_sc_hd__mux2_2 _0655_ (
    .A0(\captured_wdata[26] ),
    .A1(apb_pwdata[26]),
    .S(_0298_),
    .X(_0306_)
  );
  sky130_fd_sc_hd__buf_1 _0656_ (
    .A(_0306_),
    .X(_0044_)
  );
  sky130_fd_sc_hd__mux2_2 _0657_ (
    .A0(\captured_wdata[27] ),
    .A1(apb_pwdata[27]),
    .S(_0298_),
    .X(_0307_)
  );
  sky130_fd_sc_hd__buf_1 _0658_ (
    .A(_0307_),
    .X(_0045_)
  );
  sky130_fd_sc_hd__mux2_2 _0659_ (
    .A0(\captured_wdata[28] ),
    .A1(apb_pwdata[28]),
    .S(_0298_),
    .X(_0308_)
  );
  sky130_fd_sc_hd__buf_1 _0660_ (
    .A(_0308_),
    .X(_0046_)
  );
  sky130_fd_sc_hd__mux2_2 _0661_ (
    .A0(\captured_wdata[29] ),
    .A1(apb_pwdata[29]),
    .S(_0177_),
    .X(_0309_)
  );
  sky130_fd_sc_hd__buf_1 _0662_ (
    .A(_0309_),
    .X(_0047_)
  );
  sky130_fd_sc_hd__mux2_2 _0663_ (
    .A0(\captured_wdata[30] ),
    .A1(apb_pwdata[30]),
    .S(_0177_),
    .X(_0310_)
  );
  sky130_fd_sc_hd__buf_1 _0664_ (
    .A(_0310_),
    .X(_0048_)
  );
  sky130_fd_sc_hd__mux2_2 _0665_ (
    .A0(\captured_wdata[31] ),
    .A1(apb_pwdata[31]),
    .S(_0177_),
    .X(_0311_)
  );
  sky130_fd_sc_hd__buf_1 _0666_ (
    .A(_0311_),
    .X(_0049_)
  );
  sky130_fd_sc_hd__buf_1 _0667_ (
    .A(axi_awvalid),
    .X(_0312_)
  );
  sky130_fd_sc_hd__mux2_2 _0668_ (
    .A0(axi_araddr[0]),
    .A1(axi_awaddr[0]),
    .S(_0312_),
    .X(_0313_)
  );
  sky130_fd_sc_hd__o21a_2 _0669_ (
    .A1(axi_arvalid),
    .A2(axi_awvalid),
    .B1(_0181_),
    .X(_0314_)
  );
  sky130_fd_sc_hd__buf_1 _0670_ (
    .A(_0314_),
    .X(_0315_)
  );
  sky130_fd_sc_hd__mux2_2 _0671_ (
    .A0(\captured_addr[0] ),
    .A1(_0313_),
    .S(_0315_),
    .X(_0316_)
  );
  sky130_fd_sc_hd__buf_1 _0672_ (
    .A(_0316_),
    .X(_0050_)
  );
  sky130_fd_sc_hd__mux2_2 _0673_ (
    .A0(axi_araddr[1]),
    .A1(axi_awaddr[1]),
    .S(_0312_),
    .X(_0317_)
  );
  sky130_fd_sc_hd__mux2_2 _0674_ (
    .A0(\captured_addr[1] ),
    .A1(_0317_),
    .S(_0315_),
    .X(_0318_)
  );
  sky130_fd_sc_hd__buf_1 _0675_ (
    .A(_0318_),
    .X(_0051_)
  );
  sky130_fd_sc_hd__mux2_2 _0676_ (
    .A0(axi_araddr[2]),
    .A1(axi_awaddr[2]),
    .S(_0312_),
    .X(_0319_)
  );
  sky130_fd_sc_hd__mux2_2 _0677_ (
    .A0(\captured_addr[2] ),
    .A1(_0319_),
    .S(_0315_),
    .X(_0320_)
  );
  sky130_fd_sc_hd__buf_1 _0678_ (
    .A(_0320_),
    .X(_0052_)
  );
  sky130_fd_sc_hd__mux2_2 _0679_ (
    .A0(axi_araddr[3]),
    .A1(axi_awaddr[3]),
    .S(_0312_),
    .X(_0321_)
  );
  sky130_fd_sc_hd__mux2_2 _0680_ (
    .A0(\captured_addr[3] ),
    .A1(_0321_),
    .S(_0315_),
    .X(_0322_)
  );
  sky130_fd_sc_hd__buf_1 _0681_ (
    .A(_0322_),
    .X(_0053_)
  );
  sky130_fd_sc_hd__mux2_2 _0682_ (
    .A0(axi_araddr[4]),
    .A1(axi_awaddr[4]),
    .S(_0312_),
    .X(_0323_)
  );
  sky130_fd_sc_hd__mux2_2 _0683_ (
    .A0(\captured_addr[4] ),
    .A1(_0323_),
    .S(_0315_),
    .X(_0324_)
  );
  sky130_fd_sc_hd__buf_1 _0684_ (
    .A(_0324_),
    .X(_0054_)
  );
  sky130_fd_sc_hd__mux2_2 _0685_ (
    .A0(axi_araddr[5]),
    .A1(axi_awaddr[5]),
    .S(_0312_),
    .X(_0325_)
  );
  sky130_fd_sc_hd__mux2_2 _0686_ (
    .A0(\captured_addr[5] ),
    .A1(_0325_),
    .S(_0315_),
    .X(_0326_)
  );
  sky130_fd_sc_hd__buf_1 _0687_ (
    .A(_0326_),
    .X(_0055_)
  );
  sky130_fd_sc_hd__mux2_2 _0688_ (
    .A0(axi_araddr[6]),
    .A1(axi_awaddr[6]),
    .S(_0312_),
    .X(_0327_)
  );
  sky130_fd_sc_hd__mux2_2 _0689_ (
    .A0(\captured_addr[6] ),
    .A1(_0327_),
    .S(_0315_),
    .X(_0328_)
  );
  sky130_fd_sc_hd__buf_1 _0690_ (
    .A(_0328_),
    .X(_0056_)
  );
  sky130_fd_sc_hd__mux2_2 _0691_ (
    .A0(axi_araddr[7]),
    .A1(axi_awaddr[7]),
    .S(_0312_),
    .X(_0329_)
  );
  sky130_fd_sc_hd__mux2_2 _0692_ (
    .A0(\captured_addr[7] ),
    .A1(_0329_),
    .S(_0315_),
    .X(_0330_)
  );
  sky130_fd_sc_hd__buf_1 _0693_ (
    .A(_0330_),
    .X(_0057_)
  );
  sky130_fd_sc_hd__mux2_2 _0694_ (
    .A0(axi_araddr[8]),
    .A1(axi_awaddr[8]),
    .S(_0312_),
    .X(_0331_)
  );
  sky130_fd_sc_hd__mux2_2 _0695_ (
    .A0(\captured_addr[8] ),
    .A1(_0331_),
    .S(_0315_),
    .X(_0332_)
  );
  sky130_fd_sc_hd__buf_1 _0696_ (
    .A(_0332_),
    .X(_0058_)
  );
  sky130_fd_sc_hd__mux2_2 _0697_ (
    .A0(axi_araddr[9]),
    .A1(axi_awaddr[9]),
    .S(_0312_),
    .X(_0333_)
  );
  sky130_fd_sc_hd__mux2_2 _0698_ (
    .A0(\captured_addr[9] ),
    .A1(_0333_),
    .S(_0315_),
    .X(_0334_)
  );
  sky130_fd_sc_hd__buf_1 _0699_ (
    .A(_0334_),
    .X(_0059_)
  );
  sky130_fd_sc_hd__buf_1 _0700_ (
    .A(axi_awvalid),
    .X(_0335_)
  );
  sky130_fd_sc_hd__mux2_2 _0701_ (
    .A0(axi_araddr[10]),
    .A1(axi_awaddr[10]),
    .S(_0335_),
    .X(_0336_)
  );
  sky130_fd_sc_hd__buf_1 _0702_ (
    .A(_0314_),
    .X(_0337_)
  );
  sky130_fd_sc_hd__mux2_2 _0703_ (
    .A0(\captured_addr[10] ),
    .A1(_0336_),
    .S(_0337_),
    .X(_0338_)
  );
  sky130_fd_sc_hd__buf_1 _0704_ (
    .A(_0338_),
    .X(_0060_)
  );
  sky130_fd_sc_hd__mux2_2 _0705_ (
    .A0(axi_araddr[11]),
    .A1(axi_awaddr[11]),
    .S(_0335_),
    .X(_0339_)
  );
  sky130_fd_sc_hd__mux2_2 _0706_ (
    .A0(\captured_addr[11] ),
    .A1(_0339_),
    .S(_0337_),
    .X(_0340_)
  );
  sky130_fd_sc_hd__buf_1 _0707_ (
    .A(_0340_),
    .X(_0061_)
  );
  sky130_fd_sc_hd__mux2_2 _0708_ (
    .A0(axi_araddr[12]),
    .A1(axi_awaddr[12]),
    .S(_0335_),
    .X(_0341_)
  );
  sky130_fd_sc_hd__mux2_2 _0709_ (
    .A0(\captured_addr[12] ),
    .A1(_0341_),
    .S(_0337_),
    .X(_0342_)
  );
  sky130_fd_sc_hd__buf_1 _0710_ (
    .A(_0342_),
    .X(_0062_)
  );
  sky130_fd_sc_hd__mux2_2 _0711_ (
    .A0(axi_araddr[13]),
    .A1(axi_awaddr[13]),
    .S(_0335_),
    .X(_0343_)
  );
  sky130_fd_sc_hd__mux2_2 _0712_ (
    .A0(\captured_addr[13] ),
    .A1(_0343_),
    .S(_0337_),
    .X(_0344_)
  );
  sky130_fd_sc_hd__buf_1 _0713_ (
    .A(_0344_),
    .X(_0063_)
  );
  sky130_fd_sc_hd__mux2_2 _0714_ (
    .A0(axi_araddr[14]),
    .A1(axi_awaddr[14]),
    .S(_0335_),
    .X(_0345_)
  );
  sky130_fd_sc_hd__mux2_2 _0715_ (
    .A0(\captured_addr[14] ),
    .A1(_0345_),
    .S(_0337_),
    .X(_0346_)
  );
  sky130_fd_sc_hd__buf_1 _0716_ (
    .A(_0346_),
    .X(_0064_)
  );
  sky130_fd_sc_hd__mux2_2 _0717_ (
    .A0(axi_araddr[15]),
    .A1(axi_awaddr[15]),
    .S(_0335_),
    .X(_0347_)
  );
  sky130_fd_sc_hd__mux2_2 _0718_ (
    .A0(\captured_addr[15] ),
    .A1(_0347_),
    .S(_0337_),
    .X(_0348_)
  );
  sky130_fd_sc_hd__buf_1 _0719_ (
    .A(_0348_),
    .X(_0065_)
  );
  sky130_fd_sc_hd__mux2_2 _0720_ (
    .A0(axi_araddr[16]),
    .A1(axi_awaddr[16]),
    .S(_0335_),
    .X(_0349_)
  );
  sky130_fd_sc_hd__mux2_2 _0721_ (
    .A0(\captured_addr[16] ),
    .A1(_0349_),
    .S(_0337_),
    .X(_0350_)
  );
  sky130_fd_sc_hd__buf_1 _0722_ (
    .A(_0350_),
    .X(_0066_)
  );
  sky130_fd_sc_hd__mux2_2 _0723_ (
    .A0(axi_araddr[17]),
    .A1(axi_awaddr[17]),
    .S(_0335_),
    .X(_0351_)
  );
  sky130_fd_sc_hd__mux2_2 _0724_ (
    .A0(\captured_addr[17] ),
    .A1(_0351_),
    .S(_0337_),
    .X(_0352_)
  );
  sky130_fd_sc_hd__buf_1 _0725_ (
    .A(_0352_),
    .X(_0067_)
  );
  sky130_fd_sc_hd__mux2_2 _0726_ (
    .A0(axi_araddr[18]),
    .A1(axi_awaddr[18]),
    .S(_0335_),
    .X(_0353_)
  );
  sky130_fd_sc_hd__mux2_2 _0727_ (
    .A0(\captured_addr[18] ),
    .A1(_0353_),
    .S(_0337_),
    .X(_0354_)
  );
  sky130_fd_sc_hd__buf_1 _0728_ (
    .A(_0354_),
    .X(_0068_)
  );
  sky130_fd_sc_hd__mux2_2 _0729_ (
    .A0(axi_araddr[19]),
    .A1(axi_awaddr[19]),
    .S(_0335_),
    .X(_0355_)
  );
  sky130_fd_sc_hd__mux2_2 _0730_ (
    .A0(\captured_addr[19] ),
    .A1(_0355_),
    .S(_0337_),
    .X(_0356_)
  );
  sky130_fd_sc_hd__buf_1 _0731_ (
    .A(_0356_),
    .X(_0069_)
  );
  sky130_fd_sc_hd__buf_1 _0732_ (
    .A(axi_awvalid),
    .X(_0357_)
  );
  sky130_fd_sc_hd__mux2_2 _0733_ (
    .A0(axi_araddr[20]),
    .A1(axi_awaddr[20]),
    .S(_0357_),
    .X(_0358_)
  );
  sky130_fd_sc_hd__buf_1 _0734_ (
    .A(_0314_),
    .X(_0359_)
  );
  sky130_fd_sc_hd__mux2_2 _0735_ (
    .A0(\captured_addr[20] ),
    .A1(_0358_),
    .S(_0359_),
    .X(_0360_)
  );
  sky130_fd_sc_hd__buf_1 _0736_ (
    .A(_0360_),
    .X(_0070_)
  );
  sky130_fd_sc_hd__mux2_2 _0737_ (
    .A0(axi_araddr[21]),
    .A1(axi_awaddr[21]),
    .S(_0357_),
    .X(_0361_)
  );
  sky130_fd_sc_hd__mux2_2 _0738_ (
    .A0(\captured_addr[21] ),
    .A1(_0361_),
    .S(_0359_),
    .X(_0362_)
  );
  sky130_fd_sc_hd__buf_1 _0739_ (
    .A(_0362_),
    .X(_0071_)
  );
  sky130_fd_sc_hd__mux2_2 _0740_ (
    .A0(axi_araddr[22]),
    .A1(axi_awaddr[22]),
    .S(_0357_),
    .X(_0363_)
  );
  sky130_fd_sc_hd__mux2_2 _0741_ (
    .A0(\captured_addr[22] ),
    .A1(_0363_),
    .S(_0359_),
    .X(_0364_)
  );
  sky130_fd_sc_hd__buf_1 _0742_ (
    .A(_0364_),
    .X(_0072_)
  );
  sky130_fd_sc_hd__mux2_2 _0743_ (
    .A0(axi_araddr[23]),
    .A1(axi_awaddr[23]),
    .S(_0357_),
    .X(_0365_)
  );
  sky130_fd_sc_hd__mux2_2 _0744_ (
    .A0(\captured_addr[23] ),
    .A1(_0365_),
    .S(_0359_),
    .X(_0366_)
  );
  sky130_fd_sc_hd__buf_1 _0745_ (
    .A(_0366_),
    .X(_0073_)
  );
  sky130_fd_sc_hd__mux2_2 _0746_ (
    .A0(axi_araddr[24]),
    .A1(axi_awaddr[24]),
    .S(_0357_),
    .X(_0367_)
  );
  sky130_fd_sc_hd__mux2_2 _0747_ (
    .A0(\captured_addr[24] ),
    .A1(_0367_),
    .S(_0359_),
    .X(_0368_)
  );
  sky130_fd_sc_hd__buf_1 _0748_ (
    .A(_0368_),
    .X(_0074_)
  );
  sky130_fd_sc_hd__mux2_2 _0749_ (
    .A0(axi_araddr[25]),
    .A1(axi_awaddr[25]),
    .S(_0357_),
    .X(_0369_)
  );
  sky130_fd_sc_hd__mux2_2 _0750_ (
    .A0(\captured_addr[25] ),
    .A1(_0369_),
    .S(_0359_),
    .X(_0370_)
  );
  sky130_fd_sc_hd__buf_1 _0751_ (
    .A(_0370_),
    .X(_0075_)
  );
  sky130_fd_sc_hd__mux2_2 _0752_ (
    .A0(axi_araddr[26]),
    .A1(axi_awaddr[26]),
    .S(_0357_),
    .X(_0371_)
  );
  sky130_fd_sc_hd__mux2_2 _0753_ (
    .A0(\captured_addr[26] ),
    .A1(_0371_),
    .S(_0359_),
    .X(_0372_)
  );
  sky130_fd_sc_hd__buf_1 _0754_ (
    .A(_0372_),
    .X(_0076_)
  );
  sky130_fd_sc_hd__mux2_2 _0755_ (
    .A0(axi_araddr[27]),
    .A1(axi_awaddr[27]),
    .S(_0357_),
    .X(_0373_)
  );
  sky130_fd_sc_hd__mux2_2 _0756_ (
    .A0(\captured_addr[27] ),
    .A1(_0373_),
    .S(_0359_),
    .X(_0374_)
  );
  sky130_fd_sc_hd__buf_1 _0757_ (
    .A(_0374_),
    .X(_0077_)
  );
  sky130_fd_sc_hd__mux2_2 _0758_ (
    .A0(axi_araddr[28]),
    .A1(axi_awaddr[28]),
    .S(_0357_),
    .X(_0375_)
  );
  sky130_fd_sc_hd__mux2_2 _0759_ (
    .A0(\captured_addr[28] ),
    .A1(_0375_),
    .S(_0359_),
    .X(_0376_)
  );
  sky130_fd_sc_hd__buf_1 _0760_ (
    .A(_0376_),
    .X(_0078_)
  );
  sky130_fd_sc_hd__mux2_2 _0761_ (
    .A0(axi_araddr[29]),
    .A1(axi_awaddr[29]),
    .S(_0357_),
    .X(_0377_)
  );
  sky130_fd_sc_hd__mux2_2 _0762_ (
    .A0(\captured_addr[29] ),
    .A1(_0377_),
    .S(_0359_),
    .X(_0378_)
  );
  sky130_fd_sc_hd__buf_1 _0763_ (
    .A(_0378_),
    .X(_0079_)
  );
  sky130_fd_sc_hd__mux2_2 _0764_ (
    .A0(axi_araddr[30]),
    .A1(axi_awaddr[30]),
    .S(axi_awvalid),
    .X(_0379_)
  );
  sky130_fd_sc_hd__mux2_2 _0765_ (
    .A0(\captured_addr[30] ),
    .A1(_0379_),
    .S(_0314_),
    .X(_0380_)
  );
  sky130_fd_sc_hd__buf_1 _0766_ (
    .A(_0380_),
    .X(_0080_)
  );
  sky130_fd_sc_hd__mux2_2 _0767_ (
    .A0(axi_araddr[31]),
    .A1(axi_awaddr[31]),
    .S(axi_awvalid),
    .X(_0381_)
  );
  sky130_fd_sc_hd__mux2_2 _0768_ (
    .A0(\captured_addr[31] ),
    .A1(_0381_),
    .S(_0314_),
    .X(_0382_)
  );
  sky130_fd_sc_hd__buf_1 _0769_ (
    .A(_0382_),
    .X(_0081_)
  );
  sky130_fd_sc_hd__mux2_2 _0770_ (
    .A0(\captured_wdata[0] ),
    .A1(axi_wdata[0]),
    .S(_0003_),
    .X(_0383_)
  );
  sky130_fd_sc_hd__buf_1 _0771_ (
    .A(_0383_),
    .X(_0082_)
  );
  sky130_fd_sc_hd__mux2_2 _0772_ (
    .A0(\captured_wdata[1] ),
    .A1(axi_wdata[1]),
    .S(_0003_),
    .X(_0384_)
  );
  sky130_fd_sc_hd__buf_1 _0773_ (
    .A(_0384_),
    .X(_0083_)
  );
  sky130_fd_sc_hd__mux2_2 _0774_ (
    .A0(\captured_wdata[2] ),
    .A1(axi_wdata[2]),
    .S(_0003_),
    .X(_0385_)
  );
  sky130_fd_sc_hd__buf_1 _0775_ (
    .A(_0385_),
    .X(_0084_)
  );
  sky130_fd_sc_hd__mux2_2 _0776_ (
    .A0(\captured_wdata[3] ),
    .A1(axi_wdata[3]),
    .S(_0003_),
    .X(_0386_)
  );
  sky130_fd_sc_hd__buf_1 _0777_ (
    .A(_0386_),
    .X(_0085_)
  );
  sky130_fd_sc_hd__mux2_2 _0778_ (
    .A0(\captured_wdata[4] ),
    .A1(axi_wdata[4]),
    .S(_0003_),
    .X(_0387_)
  );
  sky130_fd_sc_hd__buf_1 _0779_ (
    .A(_0387_),
    .X(_0086_)
  );
  sky130_fd_sc_hd__mux2_2 _0780_ (
    .A0(\captured_wdata[5] ),
    .A1(axi_wdata[5]),
    .S(_0003_),
    .X(_0388_)
  );
  sky130_fd_sc_hd__buf_1 _0781_ (
    .A(_0388_),
    .X(_0087_)
  );
  sky130_fd_sc_hd__mux2_2 _0782_ (
    .A0(\captured_wdata[6] ),
    .A1(axi_wdata[6]),
    .S(_0003_),
    .X(_0389_)
  );
  sky130_fd_sc_hd__buf_1 _0783_ (
    .A(_0389_),
    .X(_0088_)
  );
  sky130_fd_sc_hd__mux2_2 _0784_ (
    .A0(\captured_wdata[7] ),
    .A1(axi_wdata[7]),
    .S(_0003_),
    .X(_0390_)
  );
  sky130_fd_sc_hd__buf_1 _0785_ (
    .A(_0390_),
    .X(_0089_)
  );
  sky130_fd_sc_hd__mux2_2 _0786_ (
    .A0(\captured_wdata[8] ),
    .A1(axi_wdata[8]),
    .S(_0003_),
    .X(_0391_)
  );
  sky130_fd_sc_hd__buf_1 _0787_ (
    .A(_0391_),
    .X(_0090_)
  );
  sky130_fd_sc_hd__buf_1 _0788_ (
    .A(_0175_),
    .X(_0392_)
  );
  sky130_fd_sc_hd__mux2_2 _0789_ (
    .A0(\captured_wdata[9] ),
    .A1(axi_wdata[9]),
    .S(_0392_),
    .X(_0393_)
  );
  sky130_fd_sc_hd__buf_1 _0790_ (
    .A(_0393_),
    .X(_0091_)
  );
  sky130_fd_sc_hd__mux2_2 _0791_ (
    .A0(\captured_wdata[10] ),
    .A1(axi_wdata[10]),
    .S(_0392_),
    .X(_0394_)
  );
  sky130_fd_sc_hd__buf_1 _0792_ (
    .A(_0394_),
    .X(_0092_)
  );
  sky130_fd_sc_hd__mux2_2 _0793_ (
    .A0(\captured_wdata[11] ),
    .A1(axi_wdata[11]),
    .S(_0392_),
    .X(_0395_)
  );
  sky130_fd_sc_hd__buf_1 _0794_ (
    .A(_0395_),
    .X(_0093_)
  );
  sky130_fd_sc_hd__mux2_2 _0795_ (
    .A0(\captured_wdata[12] ),
    .A1(axi_wdata[12]),
    .S(_0392_),
    .X(_0396_)
  );
  sky130_fd_sc_hd__buf_1 _0796_ (
    .A(_0396_),
    .X(_0094_)
  );
  sky130_fd_sc_hd__mux2_2 _0797_ (
    .A0(\captured_wdata[13] ),
    .A1(axi_wdata[13]),
    .S(_0392_),
    .X(_0397_)
  );
  sky130_fd_sc_hd__buf_1 _0798_ (
    .A(_0397_),
    .X(_0095_)
  );
  sky130_fd_sc_hd__mux2_2 _0799_ (
    .A0(\captured_wdata[14] ),
    .A1(axi_wdata[14]),
    .S(_0392_),
    .X(_0398_)
  );
  sky130_fd_sc_hd__buf_1 _0800_ (
    .A(_0398_),
    .X(_0096_)
  );
  sky130_fd_sc_hd__mux2_2 _0801_ (
    .A0(\captured_wdata[15] ),
    .A1(axi_wdata[15]),
    .S(_0392_),
    .X(_0399_)
  );
  sky130_fd_sc_hd__buf_1 _0802_ (
    .A(_0399_),
    .X(_0097_)
  );
  sky130_fd_sc_hd__mux2_2 _0803_ (
    .A0(\captured_wdata[16] ),
    .A1(axi_wdata[16]),
    .S(_0392_),
    .X(_0400_)
  );
  sky130_fd_sc_hd__buf_1 _0804_ (
    .A(_0400_),
    .X(_0098_)
  );
  sky130_fd_sc_hd__mux2_2 _0805_ (
    .A0(\captured_wdata[17] ),
    .A1(axi_wdata[17]),
    .S(_0392_),
    .X(_0401_)
  );
  sky130_fd_sc_hd__buf_1 _0806_ (
    .A(_0401_),
    .X(_0099_)
  );
  sky130_fd_sc_hd__mux2_2 _0807_ (
    .A0(\captured_wdata[18] ),
    .A1(axi_wdata[18]),
    .S(_0392_),
    .X(_0402_)
  );
  sky130_fd_sc_hd__buf_1 _0808_ (
    .A(_0402_),
    .X(_0100_)
  );
  sky130_fd_sc_hd__buf_1 _0809_ (
    .A(_0175_),
    .X(_0403_)
  );
  sky130_fd_sc_hd__mux2_2 _0810_ (
    .A0(\captured_wdata[19] ),
    .A1(axi_wdata[19]),
    .S(_0403_),
    .X(_0404_)
  );
  sky130_fd_sc_hd__buf_1 _0811_ (
    .A(_0404_),
    .X(_0101_)
  );
  sky130_fd_sc_hd__mux2_2 _0812_ (
    .A0(\captured_wdata[20] ),
    .A1(axi_wdata[20]),
    .S(_0403_),
    .X(_0405_)
  );
  sky130_fd_sc_hd__buf_1 _0813_ (
    .A(_0405_),
    .X(_0102_)
  );
  sky130_fd_sc_hd__mux2_2 _0814_ (
    .A0(\captured_wdata[21] ),
    .A1(axi_wdata[21]),
    .S(_0403_),
    .X(_0406_)
  );
  sky130_fd_sc_hd__buf_1 _0815_ (
    .A(_0406_),
    .X(_0103_)
  );
  sky130_fd_sc_hd__mux2_2 _0816_ (
    .A0(\captured_wdata[22] ),
    .A1(axi_wdata[22]),
    .S(_0403_),
    .X(_0407_)
  );
  sky130_fd_sc_hd__buf_1 _0817_ (
    .A(_0407_),
    .X(_0104_)
  );
  sky130_fd_sc_hd__mux2_2 _0818_ (
    .A0(\captured_wdata[23] ),
    .A1(axi_wdata[23]),
    .S(_0403_),
    .X(_0408_)
  );
  sky130_fd_sc_hd__buf_1 _0819_ (
    .A(_0408_),
    .X(_0105_)
  );
  sky130_fd_sc_hd__mux2_2 _0820_ (
    .A0(\captured_wdata[24] ),
    .A1(axi_wdata[24]),
    .S(_0403_),
    .X(_0409_)
  );
  sky130_fd_sc_hd__buf_1 _0821_ (
    .A(_0409_),
    .X(_0106_)
  );
  sky130_fd_sc_hd__mux2_2 _0822_ (
    .A0(\captured_wdata[25] ),
    .A1(axi_wdata[25]),
    .S(_0403_),
    .X(_0410_)
  );
  sky130_fd_sc_hd__buf_1 _0823_ (
    .A(_0410_),
    .X(_0107_)
  );
  sky130_fd_sc_hd__mux2_2 _0824_ (
    .A0(\captured_wdata[26] ),
    .A1(axi_wdata[26]),
    .S(_0403_),
    .X(_0411_)
  );
  sky130_fd_sc_hd__buf_1 _0825_ (
    .A(_0411_),
    .X(_0108_)
  );
  sky130_fd_sc_hd__mux2_2 _0826_ (
    .A0(\captured_wdata[27] ),
    .A1(axi_wdata[27]),
    .S(_0403_),
    .X(_0412_)
  );
  sky130_fd_sc_hd__buf_1 _0827_ (
    .A(_0412_),
    .X(_0109_)
  );
  sky130_fd_sc_hd__mux2_2 _0828_ (
    .A0(\captured_wdata[28] ),
    .A1(axi_wdata[28]),
    .S(_0403_),
    .X(_0413_)
  );
  sky130_fd_sc_hd__buf_1 _0829_ (
    .A(_0413_),
    .X(_0110_)
  );
  sky130_fd_sc_hd__mux2_2 _0830_ (
    .A0(\captured_wdata[29] ),
    .A1(axi_wdata[29]),
    .S(_0175_),
    .X(_0414_)
  );
  sky130_fd_sc_hd__buf_1 _0831_ (
    .A(_0414_),
    .X(_0111_)
  );
  sky130_fd_sc_hd__mux2_2 _0832_ (
    .A0(\captured_wdata[30] ),
    .A1(axi_wdata[30]),
    .S(_0175_),
    .X(_0415_)
  );
  sky130_fd_sc_hd__buf_1 _0833_ (
    .A(_0415_),
    .X(_0112_)
  );
  sky130_fd_sc_hd__mux2_2 _0834_ (
    .A0(\captured_wdata[31] ),
    .A1(axi_wdata[31]),
    .S(_0175_),
    .X(_0416_)
  );
  sky130_fd_sc_hd__buf_1 _0835_ (
    .A(_0416_),
    .X(_0113_)
  );
  sky130_fd_sc_hd__dfxtp_2 _0836_ (
    .CLK(axi_aclk),
    .D(_0114_),
    .Q(axi_rresp[1])
  );
  sky130_fd_sc_hd__dfrtp_2 _0837_ (
    .CLK(axi_aclk),
    .D(_0115_),
    .Q(\current_state[0] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0838_ (
    .CLK(axi_aclk),
    .D(_0116_),
    .Q(\current_state[1] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0839_ (
    .CLK(axi_aclk),
    .D(_0117_),
    .Q(\current_state[2] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0840_ (
    .CLK(axi_aclk),
    .D(_0417_),
    .Q(axi_awready),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0841_ (
    .CLK(axi_aclk),
    .D(_0003_),
    .Q(axi_wready),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0842_ (
    .CLK(axi_aclk),
    .D(_0002_),
    .Q(axi_arready),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0843_ (
    .CLK(axi_aclk),
    .D(_0118_),
    .Q(axi_bvalid),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfxtp_2 _0844_ (
    .CLK(axi_aclk),
    .D(_0119_),
    .Q(axi_rdata[0])
  );
  sky130_fd_sc_hd__dfxtp_2 _0845_ (
    .CLK(axi_aclk),
    .D(_0120_),
    .Q(axi_rdata[1])
  );
  sky130_fd_sc_hd__dfxtp_2 _0846_ (
    .CLK(axi_aclk),
    .D(_0121_),
    .Q(axi_rdata[2])
  );
  sky130_fd_sc_hd__dfxtp_2 _0847_ (
    .CLK(axi_aclk),
    .D(_0122_),
    .Q(axi_rdata[3])
  );
  sky130_fd_sc_hd__dfxtp_2 _0848_ (
    .CLK(axi_aclk),
    .D(_0123_),
    .Q(axi_rdata[4])
  );
  sky130_fd_sc_hd__dfxtp_2 _0849_ (
    .CLK(axi_aclk),
    .D(_0124_),
    .Q(axi_rdata[5])
  );
  sky130_fd_sc_hd__dfxtp_2 _0850_ (
    .CLK(axi_aclk),
    .D(_0125_),
    .Q(axi_rdata[6])
  );
  sky130_fd_sc_hd__dfxtp_2 _0851_ (
    .CLK(axi_aclk),
    .D(_0126_),
    .Q(axi_rdata[7])
  );
  sky130_fd_sc_hd__dfxtp_2 _0852_ (
    .CLK(axi_aclk),
    .D(_0127_),
    .Q(axi_rdata[8])
  );
  sky130_fd_sc_hd__dfxtp_2 _0853_ (
    .CLK(axi_aclk),
    .D(_0128_),
    .Q(axi_rdata[9])
  );
  sky130_fd_sc_hd__dfxtp_2 _0854_ (
    .CLK(axi_aclk),
    .D(_0129_),
    .Q(axi_rdata[10])
  );
  sky130_fd_sc_hd__dfxtp_2 _0855_ (
    .CLK(axi_aclk),
    .D(_0130_),
    .Q(axi_rdata[11])
  );
  sky130_fd_sc_hd__dfxtp_2 _0856_ (
    .CLK(axi_aclk),
    .D(_0131_),
    .Q(axi_rdata[12])
  );
  sky130_fd_sc_hd__dfxtp_2 _0857_ (
    .CLK(axi_aclk),
    .D(_0132_),
    .Q(axi_rdata[13])
  );
  sky130_fd_sc_hd__dfxtp_2 _0858_ (
    .CLK(axi_aclk),
    .D(_0133_),
    .Q(axi_rdata[14])
  );
  sky130_fd_sc_hd__dfxtp_2 _0859_ (
    .CLK(axi_aclk),
    .D(_0134_),
    .Q(axi_rdata[15])
  );
  sky130_fd_sc_hd__dfxtp_2 _0860_ (
    .CLK(axi_aclk),
    .D(_0135_),
    .Q(axi_rdata[16])
  );
  sky130_fd_sc_hd__dfxtp_2 _0861_ (
    .CLK(axi_aclk),
    .D(_0136_),
    .Q(axi_rdata[17])
  );
  sky130_fd_sc_hd__dfxtp_2 _0862_ (
    .CLK(axi_aclk),
    .D(_0137_),
    .Q(axi_rdata[18])
  );
  sky130_fd_sc_hd__dfxtp_2 _0863_ (
    .CLK(axi_aclk),
    .D(_0138_),
    .Q(axi_rdata[19])
  );
  sky130_fd_sc_hd__dfxtp_2 _0864_ (
    .CLK(axi_aclk),
    .D(_0139_),
    .Q(axi_rdata[20])
  );
  sky130_fd_sc_hd__dfxtp_2 _0865_ (
    .CLK(axi_aclk),
    .D(_0140_),
    .Q(axi_rdata[21])
  );
  sky130_fd_sc_hd__dfxtp_2 _0866_ (
    .CLK(axi_aclk),
    .D(_0141_),
    .Q(axi_rdata[22])
  );
  sky130_fd_sc_hd__dfxtp_2 _0867_ (
    .CLK(axi_aclk),
    .D(_0142_),
    .Q(axi_rdata[23])
  );
  sky130_fd_sc_hd__dfxtp_2 _0868_ (
    .CLK(axi_aclk),
    .D(_0143_),
    .Q(axi_rdata[24])
  );
  sky130_fd_sc_hd__dfxtp_2 _0869_ (
    .CLK(axi_aclk),
    .D(_0144_),
    .Q(axi_rdata[25])
  );
  sky130_fd_sc_hd__dfxtp_2 _0870_ (
    .CLK(axi_aclk),
    .D(_0145_),
    .Q(axi_rdata[26])
  );
  sky130_fd_sc_hd__dfxtp_2 _0871_ (
    .CLK(axi_aclk),
    .D(_0146_),
    .Q(axi_rdata[27])
  );
  sky130_fd_sc_hd__dfxtp_2 _0872_ (
    .CLK(axi_aclk),
    .D(_0147_),
    .Q(axi_rdata[28])
  );
  sky130_fd_sc_hd__dfxtp_2 _0873_ (
    .CLK(axi_aclk),
    .D(_0148_),
    .Q(axi_rdata[29])
  );
  sky130_fd_sc_hd__dfxtp_2 _0874_ (
    .CLK(axi_aclk),
    .D(_0149_),
    .Q(axi_rdata[30])
  );
  sky130_fd_sc_hd__dfxtp_2 _0875_ (
    .CLK(axi_aclk),
    .D(_0150_),
    .Q(axi_rdata[31])
  );
  sky130_fd_sc_hd__dfxtp_2 _0876_ (
    .CLK(axi_aclk),
    .D(_0151_),
    .Q(axi_bresp[1])
  );
  sky130_fd_sc_hd__dfrtp_2 _0877_ (
    .CLK(axi_aclk),
    .D(_0152_),
    .Q(axi_rvalid),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0878_ (
    .CLK(axi_aclk),
    .D(_0153_),
    .Q(apb_paddr[0]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0879_ (
    .CLK(axi_aclk),
    .D(_0154_),
    .Q(apb_paddr[1]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0880_ (
    .CLK(axi_aclk),
    .D(_0155_),
    .Q(apb_paddr[2]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0881_ (
    .CLK(axi_aclk),
    .D(_0156_),
    .Q(apb_paddr[3]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0882_ (
    .CLK(axi_aclk),
    .D(_0157_),
    .Q(apb_paddr[4]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0883_ (
    .CLK(axi_aclk),
    .D(_0158_),
    .Q(apb_paddr[5]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0884_ (
    .CLK(axi_aclk),
    .D(_0159_),
    .Q(apb_paddr[6]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0885_ (
    .CLK(axi_aclk),
    .D(_0160_),
    .Q(apb_paddr[7]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0886_ (
    .CLK(axi_aclk),
    .D(_0161_),
    .Q(apb_paddr[8]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0887_ (
    .CLK(axi_aclk),
    .D(_0162_),
    .Q(apb_paddr[9]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0888_ (
    .CLK(axi_aclk),
    .D(_0163_),
    .Q(apb_paddr[10]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0889_ (
    .CLK(axi_aclk),
    .D(_0164_),
    .Q(apb_paddr[11]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0890_ (
    .CLK(axi_aclk),
    .D(_0165_),
    .Q(apb_paddr[12]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0891_ (
    .CLK(axi_aclk),
    .D(_0166_),
    .Q(apb_paddr[13]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0892_ (
    .CLK(axi_aclk),
    .D(_0167_),
    .Q(apb_paddr[14]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0893_ (
    .CLK(axi_aclk),
    .D(_0168_),
    .Q(apb_paddr[15]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0894_ (
    .CLK(axi_aclk),
    .D(_0169_),
    .Q(apb_paddr[16]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0895_ (
    .CLK(axi_aclk),
    .D(_0170_),
    .Q(apb_paddr[17]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0896_ (
    .CLK(axi_aclk),
    .D(_0171_),
    .Q(apb_paddr[18]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0897_ (
    .CLK(axi_aclk),
    .D(_0004_),
    .Q(apb_paddr[19]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0898_ (
    .CLK(axi_aclk),
    .D(_0005_),
    .Q(apb_paddr[20]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0899_ (
    .CLK(axi_aclk),
    .D(_0006_),
    .Q(apb_paddr[21]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0900_ (
    .CLK(axi_aclk),
    .D(_0007_),
    .Q(apb_paddr[22]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0901_ (
    .CLK(axi_aclk),
    .D(_0008_),
    .Q(apb_paddr[23]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0902_ (
    .CLK(axi_aclk),
    .D(_0009_),
    .Q(apb_paddr[24]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0903_ (
    .CLK(axi_aclk),
    .D(_0010_),
    .Q(apb_paddr[25]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0904_ (
    .CLK(axi_aclk),
    .D(_0011_),
    .Q(apb_paddr[26]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0905_ (
    .CLK(axi_aclk),
    .D(_0012_),
    .Q(apb_paddr[27]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0906_ (
    .CLK(axi_aclk),
    .D(_0013_),
    .Q(apb_paddr[28]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0907_ (
    .CLK(axi_aclk),
    .D(_0014_),
    .Q(apb_paddr[29]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0908_ (
    .CLK(axi_aclk),
    .D(_0015_),
    .Q(apb_paddr[30]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0909_ (
    .CLK(axi_aclk),
    .D(_0016_),
    .Q(apb_paddr[31]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0910_ (
    .CLK(axi_aclk),
    .D(_0001_),
    .Q(apb_psel),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0911_ (
    .CLK(axi_aclk),
    .D(_0000_),
    .Q(apb_penable),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0912_ (
    .CLK(axi_aclk),
    .D(_0017_),
    .Q(apb_pwrite),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0913_ (
    .CLK(axi_aclk),
    .D(_0018_),
    .Q(apb_pwdata[0]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0914_ (
    .CLK(axi_aclk),
    .D(_0019_),
    .Q(apb_pwdata[1]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0915_ (
    .CLK(axi_aclk),
    .D(_0020_),
    .Q(apb_pwdata[2]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0916_ (
    .CLK(axi_aclk),
    .D(_0021_),
    .Q(apb_pwdata[3]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0917_ (
    .CLK(axi_aclk),
    .D(_0022_),
    .Q(apb_pwdata[4]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0918_ (
    .CLK(axi_aclk),
    .D(_0023_),
    .Q(apb_pwdata[5]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0919_ (
    .CLK(axi_aclk),
    .D(_0024_),
    .Q(apb_pwdata[6]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0920_ (
    .CLK(axi_aclk),
    .D(_0025_),
    .Q(apb_pwdata[7]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0921_ (
    .CLK(axi_aclk),
    .D(_0026_),
    .Q(apb_pwdata[8]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0922_ (
    .CLK(axi_aclk),
    .D(_0027_),
    .Q(apb_pwdata[9]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0923_ (
    .CLK(axi_aclk),
    .D(_0028_),
    .Q(apb_pwdata[10]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0924_ (
    .CLK(axi_aclk),
    .D(_0029_),
    .Q(apb_pwdata[11]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0925_ (
    .CLK(axi_aclk),
    .D(_0030_),
    .Q(apb_pwdata[12]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0926_ (
    .CLK(axi_aclk),
    .D(_0031_),
    .Q(apb_pwdata[13]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0927_ (
    .CLK(axi_aclk),
    .D(_0032_),
    .Q(apb_pwdata[14]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0928_ (
    .CLK(axi_aclk),
    .D(_0033_),
    .Q(apb_pwdata[15]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0929_ (
    .CLK(axi_aclk),
    .D(_0034_),
    .Q(apb_pwdata[16]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0930_ (
    .CLK(axi_aclk),
    .D(_0035_),
    .Q(apb_pwdata[17]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0931_ (
    .CLK(axi_aclk),
    .D(_0036_),
    .Q(apb_pwdata[18]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0932_ (
    .CLK(axi_aclk),
    .D(_0037_),
    .Q(apb_pwdata[19]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0933_ (
    .CLK(axi_aclk),
    .D(_0038_),
    .Q(apb_pwdata[20]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0934_ (
    .CLK(axi_aclk),
    .D(_0039_),
    .Q(apb_pwdata[21]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0935_ (
    .CLK(axi_aclk),
    .D(_0040_),
    .Q(apb_pwdata[22]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0936_ (
    .CLK(axi_aclk),
    .D(_0041_),
    .Q(apb_pwdata[23]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0937_ (
    .CLK(axi_aclk),
    .D(_0042_),
    .Q(apb_pwdata[24]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0938_ (
    .CLK(axi_aclk),
    .D(_0043_),
    .Q(apb_pwdata[25]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0939_ (
    .CLK(axi_aclk),
    .D(_0044_),
    .Q(apb_pwdata[26]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0940_ (
    .CLK(axi_aclk),
    .D(_0045_),
    .Q(apb_pwdata[27]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0941_ (
    .CLK(axi_aclk),
    .D(_0046_),
    .Q(apb_pwdata[28]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0942_ (
    .CLK(axi_aclk),
    .D(_0047_),
    .Q(apb_pwdata[29]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0943_ (
    .CLK(axi_aclk),
    .D(_0048_),
    .Q(apb_pwdata[30]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0944_ (
    .CLK(axi_aclk),
    .D(_0049_),
    .Q(apb_pwdata[31]),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0945_ (
    .CLK(axi_aclk),
    .D(_0050_),
    .Q(\captured_addr[0] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0946_ (
    .CLK(axi_aclk),
    .D(_0051_),
    .Q(\captured_addr[1] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0947_ (
    .CLK(axi_aclk),
    .D(_0052_),
    .Q(\captured_addr[2] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0948_ (
    .CLK(axi_aclk),
    .D(_0053_),
    .Q(\captured_addr[3] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0949_ (
    .CLK(axi_aclk),
    .D(_0054_),
    .Q(\captured_addr[4] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0950_ (
    .CLK(axi_aclk),
    .D(_0055_),
    .Q(\captured_addr[5] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0951_ (
    .CLK(axi_aclk),
    .D(_0056_),
    .Q(\captured_addr[6] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0952_ (
    .CLK(axi_aclk),
    .D(_0057_),
    .Q(\captured_addr[7] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0953_ (
    .CLK(axi_aclk),
    .D(_0058_),
    .Q(\captured_addr[8] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0954_ (
    .CLK(axi_aclk),
    .D(_0059_),
    .Q(\captured_addr[9] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0955_ (
    .CLK(axi_aclk),
    .D(_0060_),
    .Q(\captured_addr[10] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0956_ (
    .CLK(axi_aclk),
    .D(_0061_),
    .Q(\captured_addr[11] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0957_ (
    .CLK(axi_aclk),
    .D(_0062_),
    .Q(\captured_addr[12] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0958_ (
    .CLK(axi_aclk),
    .D(_0063_),
    .Q(\captured_addr[13] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0959_ (
    .CLK(axi_aclk),
    .D(_0064_),
    .Q(\captured_addr[14] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0960_ (
    .CLK(axi_aclk),
    .D(_0065_),
    .Q(\captured_addr[15] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0961_ (
    .CLK(axi_aclk),
    .D(_0066_),
    .Q(\captured_addr[16] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0962_ (
    .CLK(axi_aclk),
    .D(_0067_),
    .Q(\captured_addr[17] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0963_ (
    .CLK(axi_aclk),
    .D(_0068_),
    .Q(\captured_addr[18] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0964_ (
    .CLK(axi_aclk),
    .D(_0069_),
    .Q(\captured_addr[19] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0965_ (
    .CLK(axi_aclk),
    .D(_0070_),
    .Q(\captured_addr[20] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0966_ (
    .CLK(axi_aclk),
    .D(_0071_),
    .Q(\captured_addr[21] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0967_ (
    .CLK(axi_aclk),
    .D(_0072_),
    .Q(\captured_addr[22] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0968_ (
    .CLK(axi_aclk),
    .D(_0073_),
    .Q(\captured_addr[23] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0969_ (
    .CLK(axi_aclk),
    .D(_0074_),
    .Q(\captured_addr[24] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0970_ (
    .CLK(axi_aclk),
    .D(_0075_),
    .Q(\captured_addr[25] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0971_ (
    .CLK(axi_aclk),
    .D(_0076_),
    .Q(\captured_addr[26] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0972_ (
    .CLK(axi_aclk),
    .D(_0077_),
    .Q(\captured_addr[27] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0973_ (
    .CLK(axi_aclk),
    .D(_0078_),
    .Q(\captured_addr[28] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0974_ (
    .CLK(axi_aclk),
    .D(_0079_),
    .Q(\captured_addr[29] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0975_ (
    .CLK(axi_aclk),
    .D(_0080_),
    .Q(\captured_addr[30] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0976_ (
    .CLK(axi_aclk),
    .D(_0081_),
    .Q(\captured_addr[31] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0977_ (
    .CLK(axi_aclk),
    .D(_0082_),
    .Q(\captured_wdata[0] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0978_ (
    .CLK(axi_aclk),
    .D(_0083_),
    .Q(\captured_wdata[1] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0979_ (
    .CLK(axi_aclk),
    .D(_0084_),
    .Q(\captured_wdata[2] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0980_ (
    .CLK(axi_aclk),
    .D(_0085_),
    .Q(\captured_wdata[3] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0981_ (
    .CLK(axi_aclk),
    .D(_0086_),
    .Q(\captured_wdata[4] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0982_ (
    .CLK(axi_aclk),
    .D(_0087_),
    .Q(\captured_wdata[5] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0983_ (
    .CLK(axi_aclk),
    .D(_0088_),
    .Q(\captured_wdata[6] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0984_ (
    .CLK(axi_aclk),
    .D(_0089_),
    .Q(\captured_wdata[7] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0985_ (
    .CLK(axi_aclk),
    .D(_0090_),
    .Q(\captured_wdata[8] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0986_ (
    .CLK(axi_aclk),
    .D(_0091_),
    .Q(\captured_wdata[9] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0987_ (
    .CLK(axi_aclk),
    .D(_0092_),
    .Q(\captured_wdata[10] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0988_ (
    .CLK(axi_aclk),
    .D(_0093_),
    .Q(\captured_wdata[11] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0989_ (
    .CLK(axi_aclk),
    .D(_0094_),
    .Q(\captured_wdata[12] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0990_ (
    .CLK(axi_aclk),
    .D(_0095_),
    .Q(\captured_wdata[13] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0991_ (
    .CLK(axi_aclk),
    .D(_0096_),
    .Q(\captured_wdata[14] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0992_ (
    .CLK(axi_aclk),
    .D(_0097_),
    .Q(\captured_wdata[15] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0993_ (
    .CLK(axi_aclk),
    .D(_0098_),
    .Q(\captured_wdata[16] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0994_ (
    .CLK(axi_aclk),
    .D(_0099_),
    .Q(\captured_wdata[17] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0995_ (
    .CLK(axi_aclk),
    .D(_0100_),
    .Q(\captured_wdata[18] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0996_ (
    .CLK(axi_aclk),
    .D(_0101_),
    .Q(\captured_wdata[19] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0997_ (
    .CLK(axi_aclk),
    .D(_0102_),
    .Q(\captured_wdata[20] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0998_ (
    .CLK(axi_aclk),
    .D(_0103_),
    .Q(\captured_wdata[21] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _0999_ (
    .CLK(axi_aclk),
    .D(_0104_),
    .Q(\captured_wdata[22] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _1000_ (
    .CLK(axi_aclk),
    .D(_0105_),
    .Q(\captured_wdata[23] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _1001_ (
    .CLK(axi_aclk),
    .D(_0106_),
    .Q(\captured_wdata[24] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _1002_ (
    .CLK(axi_aclk),
    .D(_0107_),
    .Q(\captured_wdata[25] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _1003_ (
    .CLK(axi_aclk),
    .D(_0108_),
    .Q(\captured_wdata[26] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _1004_ (
    .CLK(axi_aclk),
    .D(_0109_),
    .Q(\captured_wdata[27] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _1005_ (
    .CLK(axi_aclk),
    .D(_0110_),
    .Q(\captured_wdata[28] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _1006_ (
    .CLK(axi_aclk),
    .D(_0111_),
    .Q(\captured_wdata[29] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _1007_ (
    .CLK(axi_aclk),
    .D(_0112_),
    .Q(\captured_wdata[30] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__dfrtp_2 _1008_ (
    .CLK(axi_aclk),
    .D(_0113_),
    .Q(\captured_wdata[31] ),
    .RESET_B(axi_aresetn)
  );
  sky130_fd_sc_hd__conb_1 _1009_ (
    .LO(axi_bresp[0])
  );
  sky130_fd_sc_hd__conb_1 _1010_ (
    .LO(axi_rresp[0])
  );
endmodule